### ISSUE TITLE
Stuttering audio/recording

### ISSUE THREAD

**Issue by tiagorribeiro24** [sspathak/VoiceChat#5] opened 2024-02-07 17:45 UTC
Barely can't hear anything because the audio is very stuttered. I set the SLEEPTIME to 0 and it fixed for a short amount of time. It raises a CBC padding issue and the socket times out after a few seconds. Do you know what seems to be the problem? I tried all sorts of padding, can't get past the padding issue nor the stuttering one.

This is the padding error: 
"(...) 
raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
"

**Comment by tiagorribeiro24** [comment] 2024-02-08 15:49
The stuttering problem happens everytime I try to run the app using the SLEEPTIME not on 0.
The padding error, only appears when I try to use a public server, or in other words, when I use the app in localhost/local network, it works fine.

**Comment by sspathak** [comment] 2024-02-08 18:35
The fact that it is occurring only when using a public server makes me wonder if this is caused by the `receiver-producer` thread receiving incomplete data from the `transmitter-consumer` thread.
I'll investigate this bug and the stuttering issue in more detail soon.
A temporary solution could be to change `MAX_BYTES_SEND` to a lower value like 256. However, I cannot guarantee this would fix the issue.

**Comment by tiagorribeiro24** [comment] 2024-02-09 16:50
I tried to set a lower `MAX_BYTES_SEND` value, but it didn't do me much for me. Tried with both sleep and without sleep. It always stutters me with sleep, but without it, it raises exceptions on CBC.

I think I know where's the issue though. Since for me the sleep is not working in any way, I disabled it and tried to fix the exceptions. Removed the encryption for now, because it's not a high priority for me. 
Without the encryption it still raised me some exceptions parsing some data for example, it failed to `data_len = int((data_len_raw).decode('utf8'))` and I think it's because sometimes it's transmiting "trash" data, for example, I did print the len being transmited and most of the time (the normal behaviour) it printed: 

data_raw: b'00000000000000000128' 
data_len: 128
data_raw: b'00000000000000000128' 
data_len: 128 
data_raw: b'00000000000000000128' 
data_len: 128 
data_raw: b'\x00\x00\x04\xbb\x00\x00\xf8\xba\x00\x00\xfc\xba00000000'
Exception_ValueError: invalid literal for int() with base 10: '\x00\x00\x04»\x00\x00øº\x00\x00üº00000000'

When the data raw has the exadecimals data is when it crashes, so this is why I assume, when no delays, some "trash" data is transmitted. I can be wrong here since I don't have the full picture.

**Comment by tiagorribeiro24** [comment] 2024-02-09 17:46
Another funny thing that I notice is that whoever starts the chat first, usually has all the exceptions/bad data. The second client receiving it, the voice is sound and clear. The first client, who presses the name of the 2nd client and presses enter first, on my test (I ignore this corrupted data), hears the sound very robotic.
Maybe this can help finding the problem

**Comment by sspathak** [comment] 2024-02-14 17:53
Thank you for reporting the bug. I've pushed a fix (#6 ) that should resolve the problem. Feel free to create a new issue if the problem persists.

**Closed as completed by sspathak** 2024-02-14 17:53 UTC
Labels: bug
